[package]
name = "vortex-serde"
version = { workspace = true }
description = "Vortex Serialisation"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
categories = { workspace = true }
readme = "README.md"

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
bytes = { workspace = true }
croaring = { workspace = true }
compio = { workspace = true, features = ["bytes", "macros"], optional = true }
flatbuffers = { workspace = true }
flume = { workspace = true }
futures = { workspace = true, features = ["std"] }
futures-channel = { workspace = true }
futures-executor = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
object_store = { workspace = true, optional = true }
once_cell = { workspace = true }
tokio = { workspace = true, features = [
    "io-util",
    "fs",
    "rt-multi-thread",
], optional = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true, features = ["flatbuffers"] }
vortex-error = { workspace = true }
vortex-expr = { workspace = true }
vortex-flatbuffers = { workspace = true, features = ["file"] }
vortex-scalar = { workspace = true, features = ["flatbuffers"] }
vortex-schema = { workspace = true }

[dev-dependencies]
arrow-array = { workspace = true }
arrow-ipc = { workspace = true, features = ["lz4"] }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
criterion = { workspace = true, features = ["async_futures"] }
rstest = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vortex-sampling-compressor = { path = "../vortex-sampling-compressor" }

[lints]
workspace = true

[features]
default = ["futures", "tokio", "compio"]
futures = ["futures-util/io"]
compio = ["dep:compio"]
tokio = ["dep:tokio"]
object_store = ["dep:object_store", "vortex-error/object_store"]

[[bench]]
name = "ipc_take"
harness = false

[[bench]]
name = "ipc_array_reader_take"
harness = false
