name: "Cleanup"
description: "Cleanup workers for more space"
runs:
  using: "composite"
  steps:
    - name: Cleanup workers
      shell: bash
      run: |
        sudo rm -rf \
          "$AGENT_TOOLSDIRECTORY" \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          /opt/pipx \
          /opt/ghc \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift || true
        df -h /
