[project]
name = "docs"
version = "0.1.0"
description = "Vortex documentation."
authors = []
dependencies = [
    "pydata-sphinx-theme>=0.16.0",
    "sphinx>=8.0.2",
    "vortex-array",
    "sphinx-design>=0.6.1",
]
requires-python = ">= 3.10"

[tool.uv]
managed = true
package = false

[tool.uv.sources]
vortex-array = { workspace = true }
